// Monster: elongated hospital patient silhouette.
const monster=new THREE.Group();const skin=new THREE.MeshStandardMaterial({color:0xa8aaa0,roughness:.92,metalness:0});const gown=new THREE.MeshStandardMaterial({color:0x566b68,roughness:.95});const darkSkin=new THREE.MeshStandardMaterial({color:0x4b4842,roughness:.9});const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.38,1.05,5,9),gown);torso.position.y=1.22;const head=new THREE.Mesh(new THREE.SphereGeometry(.31,14,10),skin);head.scale.set(.82,1.2,.78);head.position.set(0,2.18,-.03);monster.add(torso,head);for(const sx of [-.44,.44]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.09,1.35,4,7),skin);arm.position.set(sx,1.28,.02);arm.rotation.z=sx>0?-.18:.18;monster.add(arm);const hand=new THREE.Mesh(new THREE.SphereGeometry(.105,8,6),darkSkin);hand.position.set(sx*1.13,.49,.02);monster.add(hand)}for(const sx of [-.18,.18]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.12,1.3,4,7),darkSkin);leg.position.set(sx,.42,0);monster.add(leg)}for(const sx of [-.10,.10]){const e=new THREE.Mesh(new THREE.SphereGeometry(.028,6,5),new THREE.MeshBasicMaterial({color:0xffeee1}));e.position.set(sx,2.24,-.245);monster.add(e)}const mouth=new THREE.Mesh(new THREE.BoxGeometry(.14,.018,.02),new THREE.MeshBasicMaterial({color:0x160000}));mouth.position.set(0,2.08,-.27);monster.add(mouth);monster.position.set(18,-.02,-12.5);monster.rotation.y=Math.PI;scene.add(monster);monster.traverse(o=>{if(o.isMesh){o.castShadow=true;o.userData.monster=true}});
let monsterAwake=false,monsterHP=5,monsterDown=false,downTimer=0,monsterStun=0,monsterAttackCD=0,monsterPath=[],pathCD=0;
const NAV=.8,NX=Math.floor(42/NAV)+1,NZ=Math.floor(30/NAV)+1;function navWorld(ix,iz){return{x:-20.6+ix*NAV,z:-14.6+iz*NAV}}function worldNav(x,z){return{ix:Math.round((x+20.6)/NAV),iz:Math.round((z+14.6)/NAV)}}function navBlocked(ix,iz){const p=navWorld(ix,iz);return blocked(p.x,p.z,.22)}
function astar(sx,sz,gx,gz){const key=(x,z)=>x+','+z,open=[{x:sx,z:sz,g:0,f:0}],came=new Map(),gs=new Map([[key(sx,sz),0]]),heur=(x,z)=>Math.abs(x-gx)+Math.abs(z-gz);let guard=0;while(open.length&&guard++<3500){open.sort((a,b)=>a.f-b.f);const c=open.shift();if(c.x===gx&&c.z===gz){const path=[];let k=key(c.x,c.z),cur={x:c.x,z:c.z};path.push(cur);while(came.has(k)){cur=came.get(k);path.push(cur);k=key(cur.x,cur.z)}return path.reverse()}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const x=c.x+dx,z=c.z+dz;if(x<0||z<0||x>=NX||z>=NZ||navBlocked(x,z))continue;const nk=key(x,z),ng=c.g+1;if(ng>=(gs.get(nk)??1e9))continue;gs.set(nk,ng);came.set(nk,{x:c.x,z:c.z});open.push({x,z,g:ng,f:ng+heur(x,z)})}}return[]}
function updateMonster(dt){if(!monsterAwake||!state.alive||state.won)return;if(monsterDown){downTimer-=dt;monster.rotation.z=THREE.MathUtils.lerp(monster.rotation.z,1.45,dt*3);if(downTimer<=0){monsterDown=false;monsterHP=5;monster.rotation.z=0;monster.position.set(18,0,-12.5)}return}if(monsterStun>0){monsterStun-=dt;return}monsterAttackCD-=dt;pathCD-=dt;const d=Math.hypot(monster.position.x-camera.position.x,monster.position.z-camera.position.z);if(pathCD<=0){pathCD=d<8?.22:.48;const a=worldNav(monster.position.x,monster.position.z),b=worldNav(camera.position.x,camera.position.z);monsterPath=astar(a.ix,a.iz,b.ix,b.iz)}if(monsterPath.length>1){const p=navWorld(monsterPath[1].x,monsterPath[1].z);let dx=p.x-monster.position.x,dz=p.z-monster.position.z,l=Math.hypot(dx,dz);if(l<.18)monsterPath.shift();else{dx/=l;dz/=l;const sp=d<5?2.8:2.15;monster.position.x+=dx*sp*dt;monster.position.z+=dz*sp*dt;monster.rotation.y=Math.atan2(dx,dz)}}const threat=THREE.MathUtils.clamp(1-d/9,0,1);UI.danger.style.background=`radial-gradient(circle at center,transparent ${48-threat*18}%,rgba(105,0,0,${threat*.5}) 100%)`;if(d<1.05&&monsterAttackCD<=0){monsterAttackCD=1.0;damage(28)} }
function downMonster(){monsterDown=true;downTimer=16;message('A criatura caiu... por enquanto.',2)}
function damage(n){state.health-=n;UI.damage.style.opacity=.35;setTimeout(()=>UI.damage.style.opacity=0,90);updateHUD();hurtSound();if(state.health<=0)finish(false)}
let audioCtx,drone,droneGain;function audioStart(){if(audioCtx)return;try{audioCtx=new(window.AudioContext||window.webkitAudioContext)();drone=audioCtx.createOscillator();drone.type='sawtooth';drone.frequency.value=35;const f=audioCtx.createBiquadFilter();f.type='lowpass';f.frequency.value=85;droneGain=audioCtx.createGain();droneGain.gain.value=.011;drone.connect(f).connect(droneGain).connect(audioCtx.destination);drone.start()}catch{}}
function beep(freq=300,dur=.08,vol=.025){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}function gunSound(){if(!audioCtx)return;const b=audioCtx.createBuffer(1,audioCtx.sampleRate*.18,audioCtx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.exp(-i/(audioCtx.sampleRate*.025));const s=audioCtx.createBufferSource(),g=audioCtx.createGain();s.buffer=b;g.gain.value=.28;s.connect(g).connect(audioCtx.destination);s.start()}function hurtSound(){beep(70,.24,.09)}
let stepCD=0;function footstep(dt,moving,sprint){if(!audioCtx||!moving)return;stepCD-=dt;if(stepCD<=0){stepCD=sprint?.28:.42;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=75+Math.random()*18;g.gain.setValueAtTime(.025,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.08);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.09)}}
function finish(win){if(!state.alive)return;state.alive=false;state.won=win;document.exitPointerLock?.();UI.ending.classList.remove('hidden');$('#endEyebrow').textContent=win?'ALA DE EMERGÊNCIA LIBERADA':'REGISTRO ENCERRADO';$('#endTitle').textContent=win?'VOCÊ SAIU DO HOSPITAL.':'VOCÊ NÃO ESCAPOU.';$('#endText').textContent=win?'Você restaurou a energia, atravessou as alas restritas e encontrou a chave mestra da saída da ambulância.':'A criatura alcançou você dentro da ala de emergência.'}
$('#startBtn').addEventListener('click',async()=>{state.started=true;UI.start.classList.add('hidden');audioStart();if(audioCtx?.state==='suspended')await audioCtx.resume();if(!coarse)renderer.domElement.requestPointerLock?.()});
function promptText(n){if(!n)return'';if(n.kind==='door'){const d=n.door;if(d.open)return'[USAR] Fechar '+d.name;if(!requirementOk(d.req))return requirementText(d.req);return'[USAR] Abrir '+d.name}return'[USAR] '+n.data.label}
function updateDoors(dt){for(const d of doors)d.pivot.rotation.y=THREE.MathUtils.lerp(d.pivot.rotation.y,d.target,1-Math.pow(.001,dt));}
const mm=UI.mini.getContext('2d');function drawMap(){const w=UI.mini.width,h=UI.mini.height,sx=w/44,sz=h/30,px=x=>(x+22)*sx,pz=z=>(z+15)*sz;mm.clearRect(0,0,w,h);mm.fillStyle='#07100f';mm.fillRect(0,0,w,h);mm.strokeStyle='rgba(210,235,228,.22)';mm.lineWidth=3;for(const c of colliders){if(c.tag==='door')continue;mm.strokeRect(px(c.x1),pz(c.z1),Math.max(1,(c.x2-c.x1)*sx),Math.max(1,(c.z2-c.z1)*sz))}for(const d of doors){mm.fillStyle=d.open?'rgba(120,230,180,.45)':'rgba(225,230,215,.42)';mm.fillRect(px(d.x)-2,pz(d.z)-2,4,4)}let tx,tz,col='#ffd457';if(!state.maintKey){tx=maintKey.position.x;tz=maintKey.position.z}else if(!state.fuse){tx=fuse.position.x;tz=fuse.position.z}else if(!state.power){tx=breaker.position.x;tz=breaker.position.z}else if(!state.blueCard){tx=blueCard.position.x;tz=blueCard.position.z;col='#45d6ff'}else if(!state.redCard){tx=redCard.position.x;tz=redCard.position.z;col='#ff4758'}else if(!state.masterKey){tx=masterKey.position.x;tz=masterKey.position.z}else{tx=21;tz=0;col='#57ef96'}mm.fillStyle=col;mm.beginPath();mm.arc(px(tx),pz(tz),4.2,0,Math.PI*2);mm.fill();const md=Math.hypot(monster.position.x-camera.position.x,monster.position.z-camera.position.z);if(monsterAwake&&!monsterDown&&md<9){mm.fillStyle='#ff4b50';mm.beginPath();mm.arc(px(monster.position.x),pz(monster.position.z),4,0,Math.PI*2);mm.fill()}mm.save();mm.translate(px(camera.position.x),pz(camera.position.z));mm.rotate(-yaw);mm.fillStyle='#fff';mm.beginPath();mm.moveTo(0,-6);mm.lineTo(4,4);mm.lineTo(-4,4);mm.closePath();mm.fill();mm.restore()}
