const doors=[];
const doorFrameMat=new THREE.MeshStandardMaterial({color:0x303a39,roughness:.55,metalness:.66});
function createDoor(o){const {id,name,x,z,axis='x',req='none'}=o;const pivot=new THREE.Group();pivot.position.set(axis==='x'?x+.71:x,0,axis==='x'?z:z+.71);scene.add(pivot);const slab=new THREE.Mesh(new THREE.BoxGeometry(axis==='x'?1.42:.12,2.72,axis==='x'?.12:1.42),woodMat);slab.position.set(axis==='x'?-.71:0,1.36,axis==='x'?0:-.71);slab.castShadow=true;pivot.add(slab);const plate=new THREE.Mesh(new THREE.BoxGeometry(axis==='x'?.18:.035,.28,axis==='x'?.035:.18),metalMat);plate.position.set(axis==='x'?-1.15:-.085,1.25,axis==='x'?-.075:-1.15);pivot.add(plate);box(x,2.85,z,axis==='x'?1.8:.16,.18,axis==='x'?.16:1.8,doorFrameMat);const c=addCollider(axis==='x'?x-.78:x-.08,axis==='x'?x+.78:x+.08,axis==='x'?z-.08:z-.78,axis==='x'?z+.08:z+.78,'door');const d={id,name,x,z,axis,req,pivot,slab,collider:c,open:false,target:0,locked:req!=='none'};doors.push(d);return d}
createDoor({id:'wait',name:'Sala de espera',x:-15.8,z:2,req:'none'});createDoor({id:'nurse',name:'Posto de enfermagem',x:-6.4,z:2,req:'none'});createDoor({id:'ward',name:'Enfermaria A',x:5.7,z:2,req:'none'});createDoor({id:'pharmacy',name:'Farmácia',x:15.2,z:2,req:'power'});createDoor({id:'maint',name:'Manutenção',x:-15.8,z:-2,req:'maintKey'});createDoor({id:'security',name:'Segurança',x:-6.4,z:-2,req:'blueCard'});createDoor({id:'surgery',name:'Centro cirúrgico',x:6.2,z:-2,req:'redCard'});createDoor({id:'morgue',name:'Necrotério',x:15.4,z:-2,req:'none'});createDoor({id:'exit',name:'Saída da ambulância',x:21,z:0,axis:'z',req:'masterKey'});
const interactables=[];function addInteract(obj,type,label,extra={}){obj.userData.interact={type,label,...extra};interactables.push(obj);return obj}
function makePickup(type,x,z,color,label){const g=new THREE.Group();let core;if(type.includes('Card')){core=new THREE.Mesh(new THREE.BoxGeometry(.48,.025,.3),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.8,roughness:.3,metalness:.18}))}else if(type.includes('Key')){core=new THREE.Mesh(new THREE.BoxGeometry(.55,.08,.16),new THREE.MeshStandardMaterial({color,metalness:.8,roughness:.3}));const ring=new THREE.Mesh(new THREE.TorusGeometry(.16,.035,8,18),core.material);ring.position.x=-.36;ring.rotation.x=Math.PI/2;g.add(ring)}else if(type==='fuse'){core=new THREE.Mesh(new THREE.CylinderGeometry(.12,.12,.55,12),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.5,metalness:.55,roughness:.32}));core.rotation.z=Math.PI/2}else{core=new THREE.Mesh(new THREE.BoxGeometry(.4,.18,.5),new THREE.MeshStandardMaterial({color,roughness:.45,metalness:.4}))}g.add(core);const glow=new THREE.PointLight(color,1.2,2.7,2);glow.position.y=.1;g.add(glow);g.position.set(x,.98,z);scene.add(g);addInteract(g,type,label);return g}
const maintKey=makePickup('maintKey',-14.2,11.45,0xd2aa56,'Pegar chave da manutenção');const fuse=makePickup('fuse',-18.4,-11.8,0xffa928,'Pegar fusível industrial');const blueCard=makePickup('blueCard',18.1,12.2,0x35cfff,'Pegar cartão azul');const redCard=makePickup('redCard',-4.2,-11.6,0xe42f42,'Pegar cartão vermelho');const masterKey=makePickup('masterKey',8.05,-5.05,0xe7d6a4,'Pegar chave mestra');
function pistolModel(scale=1){const g=new THREE.Group();const slide=new THREE.Mesh(new THREE.BoxGeometry(.52,.18,.18),darkMetal);slide.position.set(0,.08,0);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,.5,10),blackMat);barrel.rotation.z=Math.PI/2;barrel.position.x=.18;const grip=new THREE.Mesh(new THREE.BoxGeometry(.18,.46,.18),blackMat);grip.position.set(-.13,-.2,0);grip.rotation.z=-.12;const trigger=new THREE.Mesh(new THREE.TorusGeometry(.08,.015,6,12,Math.PI*1.6),metalMat);trigger.rotation.y=Math.PI/2;trigger.position.set(.02,-.08,0);g.add(slide,barrel,grip,trigger);g.scale.setScalar(scale);return g}
const gunPickup=pistolModel(1);gunPickup.position.set(-7.3,.98,-5.1);gunPickup.rotation.y=.6;scene.add(gunPickup);addInteract(gunPickup,'gun','Pegar pistola de serviço');
function ammoBox(x,z,count=12){const m=box(x,.92,z,.42,.18,.28,new THREE.MeshStandardMaterial({color:0xa5783f,roughness:.55,metalness:.35}));addInteract(m,'ammo',`Pegar munição (+${count})`,{count});return m}ammoBox(-8.2,-5.5,12);ammoBox(3.3,-12.2,10);ammoBox(16.2,-6.2,8);
function medkit(x,z){const g=new THREE.Group();const b=new THREE.Mesh(new THREE.BoxGeometry(.55,.18,.4),plasticWhite);const cross1=new THREE.Mesh(new THREE.BoxGeometry(.22,.035,.07),redMat);cross1.position.y=.11;const cross2=new THREE.Mesh(new THREE.BoxGeometry(.07,.035,.22),redMat);cross2.position.y=.11;g.add(b,cross1,cross2);g.position.set(x,.92,z);scene.add(g);addInteract(g,'medkit','Usar kit médico (+35)');return g}medkit(8.4,12.7);medkit(4,-5.5);
const breaker=new THREE.Group();const bb=new THREE.Mesh(new THREE.BoxGeometry(.72,1.05,.18),darkMetal);const bl=new THREE.Mesh(new THREE.BoxGeometry(.38,.09,.03),new THREE.MeshStandardMaterial({color:0x6d1717,emissive:0x8e1010,emissiveIntensity:1.1}));bl.position.set(0,.25,-.105);breaker.add(bb,bl);breaker.position.set(-12.05,1.2,-12.5);breaker.rotation.y=-Math.PI/2;scene.add(breaker);addInteract(breaker,'breaker','Restaurar energia');
const state={started:false,alive:true,won:false,health:100,maintKey:false,fuse:false,power:false,blueCard:false,redCard:false,masterKey:false,gun:false,ammo:0,reserve:0,flash:true};
function updateHUD(){[['#iKey','maintKey'],['#iFuse','fuse'],['#iBlue','blueCard'],['#iRed','redCard'],['#iMaster','masterKey'],['#iGun','gun']].forEach(([id,k])=>$(id).classList.toggle('on',!!state[k]));UI.hp.textContent=Math.max(0,Math.ceil(state.health));UI.hpBar.style.width=`${Math.max(0,state.health)}%`;UI.power.textContent=state.power?'ON':'OFF';UI.power.style.color=state.power?'#9ff2bf':'#e6a0a0';if(state.gun){UI.ammo.style.display='block';UI.ammo.textContent=`${state.ammo} / ${state.reserve}`;UI.shoot.classList.add('visible')}else{UI.ammo.style.display='none';UI.shoot.classList.remove('visible')}}
function objective(){if(!state.maintKey)return'Procure uma chave de manutenção na recepção.';if(!state.fuse)return'Abra a manutenção e encontre um fusível.';if(!state.power)return'Instale o fusível no quadro elétrico e restaure a energia.';if(!state.blueCard)return'A energia voltou. Acesse a farmácia e procure o cartão azul.';if(!state.redCard||!state.gun)return'Use o cartão azul para entrar na segurança.';if(!state.masterKey)return'Use o cartão vermelho no centro cirúrgico e procure a chave mestra.';return'Leve a chave mestra até a saída da ambulância.'}function updateObjective(){UI.obj.textContent='Objetivo: '+objective()}
updateHUD();updateObjective();
let yaw=Math.PI/2,pitch=0;const player={radius:.34,speed:3.35,sprint:5.25};camera.position.set(-18.2,1.68,.1);const keys=new Set();let useQueued=false,shootQueued=false,flashQueued=false,runTouch=false;let stick={x:0,y:0,pointer:null,cx:0,cy:0};
function blocked(x,z,r=player.radius){if(x<-20.65||x>20.65||z<-14.65||z>14.65)return true;for(const c of colliders){if(!c.active)continue;if(x+r>c.x1&&x-r<c.x2&&z+r>c.z1&&z-r<c.z2)return true}return false}
function movePlayer(dx,dz){const nx=camera.position.x+dx,nz=camera.position.z+dz;if(!blocked(nx,camera.position.z))camera.position.x=nx;if(!blocked(camera.position.x,nz))camera.position.z=nz}
addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyE')useQueued=true;if(e.code==='KeyF')flashQueued=true;if(e.code==='KeyR')reload()});addEventListener('keyup',e=>keys.delete(e.code));
let pointerLocked=false;document.addEventListener('pointerlockchange',()=>pointerLocked=document.pointerLockElement===renderer.domElement);document.addEventListener('mousemove',e=>{if(!pointerLocked||!state.started||!state.alive)return;yaw-=e.movementX*.00205;pitch-=e.movementY*.00185;pitch=THREE.MathUtils.clamp(pitch,-1.35,1.35)});renderer.domElement.addEventListener('mousedown',e=>{if(e.button===0&&state.started&&state.gun&&!coarse)shootQueued=true;else if(state.started&&!coarse&&!pointerLocked)renderer.domElement.requestPointerLock?.()});
const zone=$('#stickZone');zone.addEventListener('pointerdown',e=>{e.preventDefault();stick.pointer=e.pointerId;zone.setPointerCapture(e.pointerId);const b=zone.getBoundingClientRect();stick.cx=b.left+b.width/2;stick.cy=b.top+b.height/2;updateStick(e)});zone.addEventListener('pointermove',e=>{if(e.pointerId===stick.pointer)updateStick(e)});function updateStick(e){let dx=e.clientX-stick.cx,dy=e.clientY-stick.cy;const max=50,l=Math.hypot(dx,dy);if(l>max){dx=dx/l*max;dy=dy/l*max}let sx=dx/max,sy=dy/max;const mag=Math.hypot(sx,sy),dead=.12;if(mag<dead){sx=sy=0}else{const m=(mag-dead)/(1-dead);sx=sx/mag*m;sy=sy/mag*m}stick.x=sx;stick.y=sy;UI.knob.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`}function clearStick(e){if(e.pointerId!==stick.pointer)return;stick.pointer=null;stick.x=stick.y=0;UI.knob.style.transform='translate(-50%,-50%)'}zone.addEventListener('pointerup',clearStick);zone.addEventListener('pointercancel',clearStick);
let look={pointer:null,x:0,y:0};renderer.domElement.addEventListener('pointerdown',e=>{if(!coarse||!state.started||e.clientX<innerWidth*.38)return;look.pointer=e.pointerId;look.x=e.clientX;look.y=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerId!==look.pointer)return;const dx=e.clientX-look.x,dy=e.clientY-look.y;look.x=e.clientX;look.y=e.clientY;yaw-=dx*.0036;pitch-=dy*.00325;pitch=THREE.MathUtils.clamp(pitch,-1.3,1.3)});function clearLook(e){if(e.pointerId===look.pointer)look.pointer=null}renderer.domElement.addEventListener('pointerup',clearLook);renderer.domElement.addEventListener('pointercancel',clearLook);
function btn(id,down,up){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();b.setPointerCapture?.(e.pointerId);down(e)});b.addEventListener('pointerup',e=>{e.preventDefault();e.stopPropagation();up?.(e)});b.addEventListener('pointercancel',e=>{e.preventDefault();up?.(e)})}btn('#useBtn',()=>useQueued=true);btn('#lightBtn',()=>flashQueued=true);btn('#runBtn',()=>{runTouch=true;UI.run.classList.add('active')},()=>{runTouch=false;UI.run.classList.remove('active')});btn('#shootBtn',()=>shootQueued=true);
function requirementOk(req){if(req==='none')return true;if(req==='power')return state.power;if(req==='maintKey')return state.maintKey;if(req==='blueCard')return state.blueCard;if(req==='redCard')return state.redCard;if(req==='masterKey')return state.masterKey&&state.power;return false}
function requirementText(req){return{power:'Sem energia.',maintKey:'Trancada. Precisa da chave da manutenção.',blueCard:'Leitor azul: acesso negado.',redCard:'Leitor vermelho: acesso negado.',masterKey:'A saída exige energia e a chave mestra.'}[req]||'Trancada.'}
let temporaryMsgTimer=0;function message(t,sec=1.8){UI.obj.textContent=t;temporaryMsgTimer=sec}
function toggleDoor(d){if(!d.open&&!requirementOk(d.req)){message(requirementText(d.req));return}d.open=!d.open;d.target=d.open?(d.axis==='x'?-Math.PI/2:Math.PI/2):0;d.collider.active=!d.open}
function nearestInteract(){const pos=camera.position;const forward=new THREE.Vector3(0,0,-1).applyEuler(new THREE.Euler(0,yaw,0,'YXZ'));let best=null,bd=2.05;for(const o of interactables){if(!o.visible)continue;const p=new THREE.Vector3();o.getWorldPosition(p);const d=Math.hypot(p.x-pos.x,p.z-pos.z);if(d<bd){const dir=new THREE.Vector3(p.x-pos.x,0,p.z-pos.z).normalize();if(forward.dot(dir)>.08){best={kind:'obj',obj:o,data:o.userData.interact,d};bd=d}}}for(const d of doors){const dist=Math.hypot(d.x-pos.x,d.z-pos.z);if(dist<bd){const dir=new THREE.Vector3(d.x-pos.x,0,d.z-pos.z).normalize();if(forward.dot(dir)>.02){best={kind:'door',door:d,d:dist};bd=dist}}}return best}
function hideObj(o){o.visible=false;o.userData.collected=true}
function interact(){const n=nearestInteract();if(!n)return;if(n.kind==='door'){toggleDoor(n.door);return}const {obj,data}=n;if(data.type==='maintKey'){state.maintKey=true;hideObj(obj)}else if(data.type==='fuse'){state.fuse=true;hideObj(obj)}else if(data.type==='blueCard'){if(!state.power){message('O armário eletrônico está sem energia.');return}state.blueCard=true;hideObj(obj)}else if(data.type==='redCard'){state.redCard=true;hideObj(obj)}else if(data.type==='masterKey'){state.masterKey=true;hideObj(obj)}else if(data.type==='gun'){state.gun=true;state.ammo=12;state.reserve=12;hideObj(obj);firstGun.visible=true}else if(data.type==='ammo'){state.reserve+=data.count;hideObj(obj)}else if(data.type==='medkit'){if(state.health>=100){message('Sua vida já está cheia.');return}state.health=Math.min(100,state.health+35);hideObj(obj)}else if(data.type==='breaker'){if(!state.fuse){message('O quadro está sem o fusível principal.');return}if(!state.power){state.power=true;bl.material.color.set(0x1e7d46);bl.material.emissive.set(0x2cff79);monsterAwake=true;ceilingLights.forEach((o,i)=>{if(o.main){o.l.intensity=o.base;o.panel.material.emissive.set(0xc9fff0);o.panel.material.emissiveIntensity=1.3}});emergencyAmbient.intensity=.29;message('ENERGIA PRINCIPAL RESTAURADA.',2.2)}}updateHUD();updateObjective()}
