import { chooseWeighted } from '../shared/rng.js';
import { cardValue } from '../shared/rules.js';

const RANKS=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const SUITS=['♠','♥','♦','♣'];
export function drawCard(rng){return{rank:RANKS[Math.floor(rng()*RANKS.length)],suit:SUITS[Math.floor(rng()*SUITS.length)]};}
function dice(rng){return 1+Math.floor(rng()*6);}
function roulette(rng,bet,choice){const n=Math.floor(rng()*37),red=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);const color=n===0?'green':red.has(n)?'red':'black',win=color===(choice==='black'?'black':'red');return{duration:3200,payout:win?bet*2:0,result:{n,color,win}};}
function slots(rng,bet){const symbols=['BAR','7','CROWN','CHERRY','BELL'];const weights=[30,6,10,30,24],pick=()=>chooseWeighted(rng,symbols.map((value,i)=>({value,weight:weights[i]})));const reels=[pick(),pick(),pick()];let mult=0;if(reels.every(x=>x==='7'))mult=10;else if(reels.every(x=>x===reels[0]))mult=5;else if(new Set(reels).size===2)mult=1.5;const payout=Math.floor(bet*mult);return{duration:2400,payout,result:{reels,mult,payout,win:payout>bet}};}
function craps(rng,bet,choice){choice=choice==='dont'?'dont':'pass';const rolls=[];let a=dice(rng),b=dice(rng),sum=a+b;rolls.push([a,b]);let pass;if([7,11].includes(sum))pass=true;else if([2,3,12].includes(sum))pass=false;else{const point=sum;for(let i=0;i<8;i++){a=dice(rng);b=dice(rng);sum=a+b;rolls.push([a,b]);if(sum===point){pass=true;break;}if(sum===7){pass=false;break;}}if(pass==null)pass=false;}const win=choice==='pass'?pass:!pass,payout=win?bet*2:0;return{duration:3100,payout,result:{rolls,choice,win,payout}};}
function wheel(rng,bet,type){const table=type==='money_wheel'?[{value:0,weight:28},{value:.5,weight:18},{value:1,weight:22},{value:2,weight:18},{value:3,weight:9},{value:5,weight:4},{value:10,weight:1}]:[{value:0,weight:20},{value:.5,weight:15},{value:1,weight:25},{value:2,weight:22},{value:4,weight:12},{value:8,weight:5},{value:15,weight:1}];const mult=chooseWeighted(rng,table),payout=Math.floor(bet*mult);return{duration:3000,payout,result:{mult,payout,win:payout>bet}};}
function race(rng,bet,choice){const pick=Math.max(1,Math.min(4,Number(choice)||1)),speeds=Array.from({length:4},()=>.7+rng()*.6),winner=speeds.indexOf(Math.max(...speeds))+1,payout=winner===pick?bet*4:0;return{duration:4800,payout,result:{pick,winner,speeds,payout,win:payout>0}};}
function plinkoLike(rng,bet,pachinko=false){const mult=chooseWeighted(rng,pachinko?[{value:0,weight:14},{value:.5,weight:22},{value:1,weight:30},{value:2,weight:18},{value:4,weight:10},{value:8,weight:5},{value:20,weight:1}]:[{value:0,weight:18},{value:.25,weight:18},{value:.5,weight:22},{value:1,weight:26},{value:2,weight:10},{value:5,weight:5},{value:10,weight:1}]);const lane=Math.floor(rng()*(pachinko?11:9)),payout=Math.floor(bet*mult);return{duration:3400,payout,result:{mult,lane,payout,win:payout>bet}};}
function penguin(rng,bet,choice){const steps=Math.max(2,Math.min(5,Number(choice)||2)),survival=Math.pow(.73,steps),win=rng()<survival,mults={2:1.8,3:2.8,4:4.6,5:7.5},mult=win?mults[steps]:0,payout=Math.floor(bet*mult);return{duration:2700,payout,result:{steps,mult,payout,win}};}
function keno(rng,bet,choice){const risk=['low','medium','high'].includes(choice)?choice:'medium',hits=Array.from({length:risk==='high'?8:risk==='low'?4:6},()=>rng()<.28).filter(Boolean).length;const maps={low:[0,.7,1.2,2.2,4],medium:[0,.4,.8,1.5,3.5,7,14],high:[0,.2,.5,1,2,4,8,18,40]};const mult=maps[risk][Math.min(hits,maps[risk].length-1)]||0,payout=Math.floor(bet*mult);return{duration:2400,payout,result:{risk,hits,mult,payout,win:payout>bet}};}
function pokerRank(cards){const vals=cards.map(c=>RANKS.indexOf(c.rank)+1).sort((a,b)=>a-b),counts={};for(const v of vals)counts[v]=(counts[v]||0)+1;const groups=Object.values(counts).sort((a,b)=>b-a),flush=cards.every(c=>c.suit===cards[0].suit),uniq=[...new Set(vals)],straight=uniq.length===5&&((uniq[4]-uniq[0]===4)||(JSON.stringify(uniq)===JSON.stringify([1,10,11,12,13])));if(straight&&flush)return['STRAIGHT FLUSH',12];if(groups[0]===4)return['FOUR OF A KIND',8];if(groups[0]===3&&groups[1]===2)return['FULL HOUSE',5];if(flush)return['FLUSH',4];if(straight)return['STRAIGHT',3];if(groups[0]===3)return['THREE OF A KIND',2.4];if(groups[0]===2&&groups[1]===2)return['TWO PAIR',1.8];if(groups[0]===2)return['PAIR',1.2];return['HIGH CARD',0];}
function poker(rng,bet){const cards=Array.from({length:5},()=>drawCard(rng)),[rank,mult]=pokerRank(cards),payout=Math.floor(bet*mult);return{duration:2600,payout,result:{cards,rank,mult,payout,win:payout>bet}};}
function baccarat(rng,bet,choice){choice=['player','banker','tie'].includes(choice)?choice:'banker';const pv=(cardValue([drawCard(rng),drawCard(rng)])%10),bv=(cardValue([drawCard(rng),drawCard(rng)])%10),outcome=pv===bv?'tie':pv>bv?'player':'banker';const mult=outcome===choice?(outcome==='tie'?8:outcome==='banker'?1.95:2):0,payout=Math.floor(bet*mult);return{duration:2800,payout,result:{player:pv,banker:bv,outcome,choice,payout,win:payout>0}};}
export function resolveInstant(machine,rng,bet,choice){switch(machine){case'roulette':return roulette(rng,bet,choice);case'slots':return slots(rng,bet);case'craps':return craps(rng,bet,choice);case'fortune_wheel':case'money_wheel':return wheel(rng,bet,machine);case'duck_race':return race(rng,bet,choice);case'plinko':return plinkoLike(rng,bet,false);case'pachinko':return plinkoLike(rng,bet,true);case'penguin_cross':return penguin(rng,bet,choice);case'keno':return keno(rng,bet,choice);case'poker':return poker(rng,bet);case'baccarat':return baccarat(rng,bet,choice);default:return null;}}
export function startProgressive(machine,rng,bet){if(machine==='hilo'){const card=drawCard(rng);return{machine,bet,rng,card,streak:0,mult:1,state:'playing'};}if(machine==='dragon_tower')return{machine,bet,rng,level:0,mult:1,state:'playing'};if(machine==='minesweeper'){const mines=new Set();while(mines.size<5)mines.add(Math.floor(rng()*25));return{machine,bet,rng,mines,revealed:new Set(),mult:1,state:'playing'};}if(machine==='crash'){const crashAt=Math.min(25,1.04+(-Math.log(Math.max(.0001,1-rng()))*.95));return{machine,bet,rng,startedAt:Date.now(),crashAt,mult:1,state:'playing'};}return null;}
export function progressivePublic(s){if(!s)return null;if(s.machine==='hilo')return{machine:s.machine,card:s.card,streak:s.streak,mult:s.mult};if(s.machine==='dragon_tower')return{machine:s.machine,level:s.level,mult:s.mult};if(s.machine==='minesweeper')return{machine:s.machine,revealed:[...s.revealed],mult:s.mult};if(s.machine==='crash')return{machine:s.machine,mult:s.mult};return null;}
export function progressiveAction(s,action){if(s.machine==='hilo'){if(action==='cashout')return{done:true,payout:Math.floor(s.bet*s.mult),result:{cashout:true,mult:s.mult,win:s.mult>1}};const next=drawCard(s.rng),cur=RANKS.indexOf(s.card.rank),nv=RANKS.indexOf(next.rank),ok=action==='high'?nv>=cur:nv<=cur;s.card=next;if(!ok)return{done:true,payout:0,result:{bust:true,card:next,mult:0,win:false}};s.streak++;s.mult=Number((s.mult*1.55).toFixed(2));return{state:progressivePublic(s)};}
if(s.machine==='dragon_tower'){if(action==='cashout')return{done:true,payout:Math.floor(s.bet*s.mult),result:{cashout:true,level:s.level,mult:s.mult,win:s.mult>1}};const survive=s.rng()<Math.max(.46,.82-s.level*.055);if(!survive)return{done:true,payout:0,result:{burned:true,level:s.level,win:false}};s.level++;s.mult=Number((s.mult*(1.36+s.level*.06)).toFixed(2));if(s.level>=8)return{done:true,payout:Math.floor(s.bet*s.mult),result:{complete:true,level:s.level,mult:s.mult,win:true}};return{state:progressivePublic(s)};}
if(s.machine==='minesweeper'){if(action==='cashout')return{done:true,payout:Math.floor(s.bet*s.mult),result:{cashout:true,revealed:[...s.revealed],mult:s.mult,win:s.mult>1}};const idx=Number(String(action).replace('tile:',''));if(!Number.isInteger(idx)||idx<0||idx>24||s.revealed.has(idx))return{state:progressivePublic(s)};if(s.mines.has(idx))return{done:true,payout:0,result:{mine:idx,revealed:[...s.revealed],win:false}};s.revealed.add(idx);s.mult=Number((1+Math.pow(s.revealed.size,1.28)*.22).toFixed(2));if(s.revealed.size>=20)return{done:true,payout:Math.floor(s.bet*s.mult),result:{clear:true,revealed:[...s.revealed],mult:s.mult,win:true}};return{state:progressivePublic(s)};}
if(s.machine==='crash'&&action==='cashout')return{done:true,payout:Math.floor(s.bet*s.mult),result:{cashout:true,mult:s.mult,win:s.mult>1}};return{state:progressivePublic(s)};}
